# Generated by Django 5.1.2 on 2024-10-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("owner", models.CharField(max_length=255)),
                ("company_type", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("since", models.DateField()),
                ("employee_range", models.CharField(max_length=50)),
            ],
        ),
    ]
