# Generated by Django 5.1.2 on 2024-10-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="employee_range",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="since",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name="company",
            table="companies",
        ),
    ]
