# Generated by Django 5.1.2 on 2024-10-16 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="company",
            table=None,
        ),
    ]
